### PR TITLE
test: subtree test

### LINKED ISSUE #2: Add tests for the subtree helpers
The two methods should be properly tested.

### PR DESCRIPTION
**Pull request by TroyTae**
I cannot continue because of error of `this` keyword.
So I wanna merge this and continue writing test in the other PR after fixing bug.

### CODE REVIEW

**Comment by TroyTae** [comment]
@AVGP I made a issue about error in [here](https://github.com/GoogleChromeLabs/dom2html/issues/13)

**Comment by AVGP** [comment]
@TroyTae Thanks so much for taking this on!

I replied to the issue you opened for the error you were seeing. Let me know if the answer doesn't help - we'll get this going together :)

**Comment by TroyTae** [comment]
@AVGP 
Thank you for your answer!
I replied in your answer in that issue.

And can you merge the other two PR?
I wanna check code coverage while writing test code :)

**Comment by AVGP** [comment]
@TroyTae I've responded and I think we can move forward with this, right?

**Comment by TroyTae** [comment]
@AVGP Yep! Now I continue to write test.

**Comment by TroyTae** [comment]
@AVGP I'm ready for review!

**Comment by AVGP** [comment]
This looks great, thank you so much for closing the last gap in testing, @TroyTae ! 🦄 

closes #2

**Pull request merged**
